Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.box_version = "~> 20221202.0.1"
    config.vm.boot_timeout = 600

    config.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 512
        v.name = "QNET-TEST-API-SERVER"
    end

    config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.provision "shell", inline: <<-SHELL
        systemctl disable apt-daily.service
        systemctl disable apt-daily.timer

        sudo apt-get update -y
        sudo apt-get install python3-venv zip -y
    SHELL
end